### ISSUE TITLE
103 . create user search component

### ISSUE THREAD

**Issue by faiyazbits** [campusrope/campusropepwa#4]
make a user search component using
https://github.com/ng-select/ng-select#readme
this component should be responsible for making the request for users as we type in the input
basically a typeahead
should have an output called userSelected emitting with the selected user

**Comment by faiyazbits** [comment]
There is helpline search component, which is already done

**Comment by faiyazbits** [comment]
component files are already created in shared.just have to write code

**Comment by devgeektech** [comment]
Yes I've checked the requirement and component which you have already created. Can you please share API to search user. so that I could move forward with integration.

In the helpline search you are just returning the id of selected helpline. so in this search we also need to send back user id or full object of user.

Question: it is single user selection of multi user selection on type-ahead.

**Comment by faiyazbits** [comment]
its a single user selection
we can emit the full object
api for users is rooturl/users

then you can use strapi filter queries like i did in helpline

**Comment by devgeektech** [comment]
Okay Thanks for the update.

**Comment by devgeektech** [comment]
I have created the search component for users to display the data according to the search key and implement the API you have provided. 

Working on to output selected user object.

**Comment by faiyazbits** [comment]
this is an issue page . please put your updates in skype.only technical things that pertains to this issue should be discusses here.its basic oss principle.
Nice work by the way.send a PR once you are done
